baseurl: /blog
url: http://ton31337.github.io

harmony:
  name: donatas abraitis
  description: 
  meta_description: > # 
    Donatas Abraitis
    ton31337
    Performance
    Networking
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Donatas Abraitis
    email: donatas.abraitis@gmail.com
    url: http://ton31337.github.io
  google_analytics_key:
  social: 
    github: ton31337
    twitter: abradona
    facebook: donatas.abraitis
  show_disclaimer: true

markdown:    kramdown
highlighter: pygments 
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

sass:
    sass_dir: assets/css/_sass
    style: :compressed
